server:
    ssl:
        key-store: classpath:keystore.p12
        key-store-password: password
        key-store-type: pkcs12
        key-alias: springboot
        key-password: password
    port: 8443

spring:
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://192.168.100.42/pi4?useTimezone=true&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false
        username: postgres
        password: 1234
    jpa:
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL95Dialect
            jdbc:
                time_zone: UTC
        hibernate:
            ddl-auto: update
    jackson:
        default-property-inclusion: non_null
    servlet:
        multipart:
            enabled: true
            file-size-threshold: 2KB
            max-file-size: 30MB
            max-request-size: 150MB

flyway:
    url: jdbc:postgresql://192.168.100.42
    schema: pi4
    user: postgres
    password: 1234

security:
    jwt:
        token:
            secret-key: 8yw9%*J$Qa93*-5zmN$EJasdasdasdd!@#asfr324fASdfr23d
            expire-lenght: 86400000 # 24h



logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
        context: DEBUG


org:
    springframework:
        security:
            config:
                annotation:
                    web:
                        builders:
                            WebSecurity:
                                debugEnabled: true