spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://db-cebreja-production.cstmbw1g9vpd.sa-east-1.rds.amazonaws.com/pi4?useTimezone=true&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false
        username: admin
        password: 2Nv4UP0m1!hM_3ukXDTkgAaBBs4S
    jpa:
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
            jdbc:
                time_zone: UTC
        hibernate:
            ddl-auto: update
    jackson:
        default-property-inclusion: non_null
    servlet:
        multipart:
            enabled: true
            file-size-threshold: 2KB
            max-file-size: 30MB
            max-request-size: 150MB

flyway:
    url: jdbc:mysql://db-cebreja-production.cstmbw1g9vpd.sa-east-1.rds.amazonaws.com/
    schema: pi4
    user: admin
    password: 2Nv4UP0m1!hM_3ukXDTkgAaBBs4S

security:
    jwt:
        token:
            secret-key: 8yw9%*J$Qa93*-5zmN$EJasdasdasdd!@#asfr324fASdfr23d
            expire-lenght: 86400000 # 24h



logging:
  level:
    org:
      springframework:
        security: DEBUG

org:
    springframework:
        security:
            config:
                annotation:
                    web:
                        builders:
                            WebSecurity:
                                debugEnabled: true