package com.gs.pi4.api.api.exception;

public enum CodeExceptionEnum {
    AUTH_REGISTER_DUPLICATED_EMAIL,
    AUTH_REGISTER_INVALID_BIRTHDAY,
    AUTH_REGISTER_PASSWORD_SMALL,
    AUTH_REGISTER_INVALID_EMAIL,
    AUTH_REGISTER_INVALID_GENDER,
    AUTH_SIGNIN_USER_NOT_FOUND,
    AUTH_BAD_CREDENTIALS,
    AUTH_INVALID_JWT,
    UNAUTHORIZED_RESOURCE_ACCESS,
    RESOURCE_NOT_FOUND,
    NON_HANDLED_ERROR;
}
