package com.gs.pi4.api.api.exception;

public enum CodeExceptionEnum {
    NON_HANDLED_ERROR,
    AUTH_REGISTER_DUPLICATED_EMAIL,
    AUTH_REGISTER_INVALID_BIRTHDAY,
    AUTH_REGISTER_PASSWORD_SMALL,
    AUTH_REGISTER_INVALID_EMAIL,
    AUTH_REGISTER_INVALID_GENDER,
    AUTH_SIGNIN_USER_NOT_FOUND,
    AUTH_BAD_CREDENTIALS,
    AUTH_INVALID_JWT,
    UNAUTHORIZED_RESOURCE_ACCESS,
    RESOURCE_NOT_FOUND,
    COMPANY_NOT_FOUND,
    PRODUCT_NOT_FOUND,
    BUDGET_REQUEST_ITEM_QUANTITY_INVALID,
    BUDGET_REQUEST_HAS_RESPONSES,
    BUDGET_REQUEST_ITEM_PRICE_INVALID,
    BUDGET_RESPONSE_IS_BUYED;
}
